### ISSUE TITLE
Update README with note how to support Xcode Previews

### ISSUE THREAD

**Issue by stonko1994** [dscyrescotti/SwiftTheming#26]
I had a hard time figuring out why Xcode Previews no longer work after adding and using `SwiftTheming` in one of my Views.

In order to make Xcode Previews working as well one need to add the setup code to the Previews as well.

```swift
struct View_Preview: PreviewProvider {
    static var previews: {
        AnyView()
            .themeProviding(defaultTheme: Theme.sampleTheme, defaultAppearance: .system)
    }
}
```

**Comment by dscyrescotti** [comment]
As the API designs to use `ThemeProvider` as an environment object, it is mandatory to inject an instance of `ThemeProvider` for the purpose of working properly on the preview. It is a similar approach of using other custom environment objects. Since it should be known with the prior knowledge, that information will not be added to README.
